#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Running with RUN"
	make j=1 w=1 asan=0 msl=1 map=non_valid_hole2 re run
fi

case $1 in
    -re|--re)
        echo "Running with RE"
        make j=1 w=1 map=non_valid_hole re
        make j=1 w=1 map=non_valid_hole run
    ;;
    *)
        echo "invalid option $1"
    ;;
esac
